#端口号配置
server:
  port: 8089
#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5533/vue-schedule?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hj.web.**.entity
  check-config-location: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #配置mybatis-plus 在更新时只更新非空和非null的字段
      update-strategy: not_empty
    banner: false
    super-mapper-class: com.baomidou.mybatisplus.core.mapper.BaseMapper

# Redis 连接配置
#redis:
#  host: localhost
#  port: 6379
#  password: your_redis_password
#  database: 0
#  timeout: 2000
#  jedis:
#    pool:
#      max-active: 100
#      max-idle: 10
#      min-idle: 1
#      max-wait: -1ms

#jwt配置
jwt:
  issuer: hj
  secret: com.hj
  #  30分钟过期
  expiration: 3600

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger - %msg%n'
  level:
    org.springframework: INFO
    com.hj: DEBUG
    org.mybatis: DEBUG

