<template>
  <div>

    <!-- Add Stage Button -->
    <div style="margin-bottom: 16px;">
        <a-button type="primary" @click="handleAdd">添加阶段</a-button>
    </div>

    <div v-if="loading">Loading stages...</div>
    <div v-else-if="error">Error loading stages: {{ error.message }}</div>
    <div v-else>
      <a-table
        :columns="columns"
        :data-source="stages"
        :row-key="'id'"
        :pagination="false"
        :loading="loading"
      >
        <!-- Use bodyCell slot to customize cell rendering -->
        <template #bodyCell="{ column, text, record }">
          <template v-if="column.key === 'createTime'">
            <span>{{ formatDateTime(text) }}</span>
          </template>
          <template v-else-if="column.key === 'updateTime'">
            <span>{{ formatDateTime(text) }}</span>
          </template>
          <template v-else-if="column.key === 'action'">
            <span>
              <a @click="handleEdit(record)">编辑</a>
              <a-divider type="vertical" />
              <a @click="handleDelete(record)">删除</a>
            </span>
          </template>
        </template>
      </a-table>

      <p v-if="stages.length === 0 && !loading && !error">No stages found.</p>
    </div>

    <!-- Edit/Add Modal -->
    <a-modal
        v-model:visible="editModalVisible"
        :title="modalTitle" 
        @ok="saveStage" 
        @cancel="cancelEdit"
        :confirmLoading="savingStage" 
    >
      <!-- Ensure currentStageData is not null -->
      <a-form
          v-if="currentStageData"
          :model="currentStageData"
          :label-col="{ span: 5 }"
          :wrapper-col="{ span: 16 }"
      >
        <a-form-item label="阶段名称" name="stageName">
          <a-input v-model:value="currentStageData.stageName" />
        </a-form-item>
        <a-form-item label="描述" name="description">
          <a-textarea v-model:value="currentStageData.description" />
        </a-form-item>
        <!-- 其他需要编辑/添加的字段 -->
      </a-form>
    </a-modal>

  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'; // Import computed
import useStageTable from '@/composable/course/stageTable';
import type { Stage } from '@/api/course/Stage';
import { message, Modal } from 'ant-design-vue';

// Use the composable, including the new addStage function
const { stages, loading, error, columns, editStage, deleteStage, addStage } = useStageTable();

// --- Time Formatting Helper ---
const formatDateTime = (datetimeString: string | null | undefined): string => {
    if (!datetimeString) {
        return '';
    }
    try {
        const date = new Date(datetimeString);
        if (isNaN(date.getTime())) {
             console.error('Invalid date string:', datetimeString);
             return datetimeString;
        }
        const year = date.getFullYear();
        const month = ('0' + (date.getMonth() + 1)).slice(-2);
        const day = ('0' + date.getDate()).slice(-2);
        const hours = ('0' + date.getHours()).slice(-2);
        const minutes = ('0' + date.getMinutes()).slice(-2);
        const seconds = ('0' + date.getSeconds()).slice(-2);

        return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
    } catch (e) {
         console.error('Error formatting date:', e);
         return datetimeString;
    }
};

// --- Edit/Add Modal State and Logic ---
const editModalVisible = ref(false);
// Use a single state variable for both adding and editing data
const currentStageData = ref<Partial<Stage> | null>(null); // Use Partial as ID might be missing for new stage
const savingStage = ref(false); // Single saving state for both

// Determine modal title based on if editingStage has an ID
const modalTitle = computed(() => currentStageData.value && currentStageData.value.id !== undefined ? '编辑阶段' : '添加阶段');


// Handle Add Button Click
const handleAdd = () => {
    console.log('Add stage');
    // Initialize currentStageData with default values for a new stage
    currentStageData.value = {
        stageName: '',
        description: null,
        // ID, createTime, updateTime will be generated by backend
    };
    editModalVisible.value = true; // Open the modal
};

// Handle Edit Button Click (updated to use currentStageData)
const handleEdit = (record: Stage) => {
  console.log('Edit stage:', record);
  // Use JSON.parse(JSON.stringify(record)) for deep copy
  currentStageData.value = JSON.parse(JSON.stringify(record));
  editModalVisible.value = true;
};

// Handle Modal Save (replaces saveEdit)
const saveStage = async () => {
  if (!currentStageData.value || !currentStageData.value.stageName) {
      message.warning('阶段名称不能为空');
      return;
  }

  savingStage.value = true;
  try {
    // Check if it's an edit operation (has ID) or add operation (no ID)
    if (currentStageData.value.id !== undefined) {
        // It's an edit operation
        await editStage(currentStageData.value as Stage); // Cast as Stage for editStage function
        message.success('阶段编辑成功！');
    } else {
        // It's an add operation
        // Ensure no ID is sent for add
        const { id, ...stageDataForAdd } = currentStageData.value; // Exclude ID
        await addStage(stageDataForAdd as { stageName: string; description: string | null }); // Cast for addStage function
        message.success('阶段添加成功！');
    }
    editModalVisible.value = false;
    currentStageData.value = null;
  } catch (error: any) {
    message.error(`操作失败: ${error.message || '未知错误'}`);
  } finally {
    savingStage.value = false;
  }
};

// Handle Modal Cancel
const cancelEdit = () => { // Renamed from cancelEdit for clarity
    console.log('Modal cancelled');
    editModalVisible.value = false;
    currentStageData.value = null; // Clear data on cancel
}


// --- Delete Operation ---
const handleDelete = (record: Stage) => {
  console.log('Delete stage:', record);
  Modal.confirm({
    title: '确认删除',
    content: `确定要删除阶段 "${record.stageName}" 吗？`,
    okText: '确定',
    okType: 'danger',
    cancelText: '取消',
    onOk: async () => {
      try {
        await deleteStage(record.id);
        message.success('阶段删除成功！');
      } catch (error: any) {
        message.error(`删除失败: ${error.message || '未知错误'}`);
      }
    },
    onCancel() {
      console.log('Delete cancelled');
    },
  });
};

// onMounted hook is inside the useStageTable composable now.
</script>

<style scoped>
/* Add or adjust styles as needed for your table component */
table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 20px;
}

th, td {
  border: 1px solid #ddd;
  padding: 8px;
  text-align: left;
}

th {
  background-color: #f2f2f2;
}
</style>
